name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      # Qualité (optionnels si pas encore configurés)
      - run: npm run typecheck --if-present
      - run: npm run lint --if-present
      - run: npm test --if-present -- --run
      # Build prod
      - run: npm run build
      # Archive du bundle pour téléchargement
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist